//
// Created by yan on 4/7/26.
//

#ifndef NUCLEOL476RG_BMP280_PORTEXPANDER_H
#define NUCLEOL476RG_BMP280_PORTEXPANDER_H

// Includes 

#include "I2C.h"

// MCP23017 registers

#define MCP23017_REGISTER_IODIRA        (0x00) // I/O DIRECTION REGISTER
#define MCP23017_REGISTER_IODIRB        (0x00) // I/O DIRECTION REGISTER
#define MCP23017_REGISTER_IPOLA         (0x00) // INPUT POLARITY REGISTER
#define MCP23017_REGISTER_IPOLB         (0x00) // INPUT POLARITY REGISTER
#define MCP23017_REGISTER_GPINTENA      (0x00) // INTERRUPT-ON-CHANGE CONTROL REGISTER
#define MCP23017_REGISTER_GPINTENB      (0x00) // INTERRUPT-ON-CHANGE CONTROL REGISTER
#define MCP23017_REGISTER_DEFVALA       (0x00) // DEFAULT COMPARE REGISTER FOR INTERRUPT-ON-CHANGE
#define MCP23017_REGISTER_DEFVALB       (0x00) // DEFAULT COMPARE REGISTER FOR INTERRUPT-ON-CHANGE
#define MCP23017_REGISTER_INTCONA       (0x00) // INTERRUPT CONTROL REGISTER
#define MCP23017_REGISTER_INTCONB       (0x00) // INTERRUPT CONTROL REGISTER
#define MCP23017_REGISTER_IOCON         (0x00) // CONFIGURATION REGISTER
#define MCP23017_REGISTER_IOCON         (0x00) // CONFIGURATION REGISTER
#define MCP23017_REGISTER_GPPUA         (0x00) // PULL-UP RESISTOR CONFIGURATION REGISTER
#define MCP23017_REGISTER_GPPUB         (0x00) // PULL-UP RESISTOR CONFIGURATION REGISTER
#define MCP23017_REGISTER_INTFA         (0x00) // INTERRUPT FLAG REGISTER
#define MCP23017_REGISTER_INTFB         (0x00) // INTERRUPT FLAG REGISTER
#define MCP23017_REGISTER_INTCAPA       (0x00) // INTERRUPT CAPTURE REGISTER
#define MCP23017_REGISTER_INTCAPB       (0x00) // INTERRUPT CAPTURE REGISTER
#define MCP23017_REGISTER_GPIOA         (0x00) // PORT REGISTER
#define MCP23017_REGISTER_GPIOB         (0x00) // PORT REGISTER
#define MCP23017_REGISTER_OLATA         (0x00) // OUTPUT LATCH REGISTER (OLAT)
#define MCP23017_REGISTER_OLATB         (0x00) // OUTPUT LATCH REGISTER (OLAT)

// Typedef MCP23017

typedef emum{
  PORT_A,
  PORT_B
}PortDef;


// Init configuartion MCP23017
int8_t PortExpanderInit(uint_8 devAdr); 

// Set configuartion Port
int8_t PortExpanderSetConfig(uint_8 devAdr, PortDef port);

// Read / Write Port 
int8_t PortExpanderReadInput(uint_8 devAdr, PortDef port, uint8_t value);
int8_t PortExpanderWriteOutput(uint_8 devAdr, PortDef port, unit8_t value);


#endif //NUCLEOL476RG_BMP280_PORTEXPANDER_H
